In [2]:
data = {
    "customer_id": [
        1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020,
        1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030
    ],

    "age": [
        25, 32, None, 45, 29, 41, 38, None, 27, 50,
        34, 28, 60, 22, None, 47, 36, 31, 44, 26,
        39, 55, None, 30, 42, 24, 48, 35, None, 52
    ],

    "gender": [
        "Male", "Female", "Female", "Male", None,
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male",
        None, "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", None, "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],

    "income": [
        50, 7000, 6500, None, 4800, 7200, 6900, 6100, None, 8500,
        6200, 5400, 12000, 3900, 5800, 9100, 6800, 6400, None, 4700,
        7600, 11000, 5900, 5300, 8300, 4200, 9800, None, 6100, 125000
    ],

    "city": [
        "Cairo", "Alexandria", "Giza", "Cairo", "Mansoura",
        None, "Alexandria", "Giza", "Cairo", "Mansoura",
        "Cairo", "Tanta", "Giza", "Alexandria", "Mansoura",
        "Cairo", None, "Tanta", "Giza", "Alexandria",
        "Cairo", "Mansoura", "Tanta", "Giza", None,
        "Cairo", "Alexandria", "Mansoura", "Tanta", "Giza"
    ],

    "education": [
        "Bachelor", "Master", "Bachelor", "PhD", "Diploma",
        "Master", None, "Bachelor", "Diploma", "PhD",
        "Bachelor", "Diploma", "PhD", "Bachelor", "Master",
        "Bachelor", "Diploma", None, "Master", "Bachelor",
        "PhD", "Master", "Diploma", "Bachelor", "PhD",
        None, "Master", "Diploma", "Bachelor", "PhD"
    ],

    "marital_status": [
        "Single", "Married", "Single", "Married", "Single",
        "Divorced", "Married", None, "Single", "Married",
        "Single", "Married", "Widowed", "Single", "Married",
        "Divorced", "Single", "Married", None, "Single",
        "Married", "Widowed", "Divorced", "Single", "Married",
        "Single", None, "Married", "Divorced", "Widowed"
    ],

    "num_purchases": [
        5, 12, 7, 20, 3, 15, None, 8, 4, 25,
        9, 6, 30, 2, 10, 18, 11, 7, None, 5,
        14, 28, 8, 6, 19, 3, 22, 12, 9, 35
    ],

    "avg_purchase_value": [
        200.5, 450.0, 300.0, 800.0, None, 520.0, 410.0, 330.0, 250.0, 950.0,
        380.0, 290.0, 1500.0, 180.0, 420.0, 760.0, None, 310.0, 680.0, 240.0,
        540.0, 1400.0, 360.0, 275.0, 820.0, 190.0, 990.0, 470.0, 340.0, 1700.0
    ],

    "membership_years": [
        1, 3, 2, 10, 1, 5, 4, 2, None, 12,
        3, 1, 15, 0.5, 2, 8, 4, 3, 6, 1,
        5, 14, None, 2, 9, 1, 11, 4, 3, 1600
    ],

    "has_credit_card": [
        "Yes", "Yes", "No", "Yes", "No",
        "Yes", "Yes", "No", "No", "Yes",
        "Yes", "No", "Yes", "No", "Yes",
        "Yes", "No", "Yes", "No", "Yes",
        "Yes", "Yes", "No", "No", "Yes",
        "No", "Yes", "Yes", "No", "Yes"
    ],

    "preferred_device": [
        "Mobile", "Laptop", "Tablet", "Mobile", "Mobile",
        "Laptop", None, "Tablet", "Mobile", "Laptop",
        "Tablet", "Mobile", "Laptop", "Mobile", "Tablet",
        "Laptop", "Mobile", None, "Tablet", "Mobile",
        "Laptop", "Laptop", "Tablet", "Mobile", "Laptop",
        "Tablet", "Mobile", "Laptop", None, "Laptop"
    ],

    "satisfaction_score": [
        8.5, 9.2, 7.8, 9.8, 6.9, 8.9, None, 7.5, 7.0, 9.9,
        8.1, 7.4, 9.7, 6.5, 8.3, 9.0, 8.6, 7.7, None, 7.2,
        8.8, 9.6, 7.9, 7.3, 9.1, 6.8, 9.4, 8.4, 7.6, 9.8
    ],
    
        "customer_level": [
        "Bronze", "Silver", "Gold", "Platinum", "Bronze",
        "Silver", "Gold", "Silver", "Bronze", "Platinum",
        "Gold", "Bronze", "Platinum", "Silver", "Gold",
        "Platinum", "Silver", "Bronze", "Gold", "Bronze",
        "Silver", "Platinum", "Gold", "Bronze", "Platinum",
        "Silver", "Gold", "Silver", "Bronze", "Platinum"
    ],

    "target": [
        1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 1
    ]
}

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame(data)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         30 non-null     int64
 1   age                 25 non-null     float64
 2   gender              27 non-null     object
 3   income              26 non-null     float64
 4   city                27 non-null     object
 5   education           27 non-null     object
 6   marital_status      27 non-null     object
 7   num_purchases       28 non-null     float64
 8   avg_purchase_value  28 non-null     float64
 9   membership_years    28 non-null     float64
 10  has_credit_card     30 non-null     object
 11  preferred_device    27 non-null     object
 12  satisfaction_score  28 non-null     float64
 13  customer_level      30 non-null     object
 14  target              30 non-null     int64
dtypes: float64(6), int64(2), object(7)
memory usage: 3.6+ KB

In [6]:
df.describe()

       customer_id   age  ...  satisfaction_score     target
count    30.000000  25.0  ...           28.000000  30.000000
mean   1015.500000  37.6  ...            8.310714   0.600000
std       8.803408  10.5  ...            1.031123   0.498273
min    1001.000000  22.0  ...            6.500000   0.000000
25%    1008.250000  29.0  ...            7.475000   0.000000
50%    1015.500000  36.0  ...            8.350000   1.000000
75%    1022.750000  45.0  ...            9.125000   1.000000
max    1030.000000  60.0  ...            9.900000   1.000000

[8 rows x 8 columns]

In [7]:
df.corr(numeric_only=True)

                    customer_id       age  ...  satisfaction_score    target
customer_id            1.000000  0.207697  ...            0.015640 -0.039306
age                    0.207697  1.000000  ...            0.874806  0.698473
income                 0.359521  0.387072  ...            0.374433  0.216451
num_purchases          0.243422  0.962754  ...            0.896094  0.689033
avg_purchase_value     0.266642  0.927572  ...            0.818260  0.589404
membership_years       0.321258  0.295899  ...            0.292051  0.151631
satisfaction_score     0.015640  0.874806  ...            1.000000  0.864462
target                -0.039306  0.698473  ...            0.864462  1.000000

[8 rows x 8 columns]

In [8]:
df.isnull().sum()

customer_id           0
age                   5
gender                3
income                4
city                  3
education             3
marital_status        3
num_purchases         2
avg_purchase_value    2
membership_years      2
has_credit_card       0
preferred_device      3
satisfaction_score    2
customer_level        0
target                0
dtype: int64

In [12]:
df.duplicated().sum()

0

In [13]:
from sklearn.preprocessing import LabelEncoder as le

In [31]:
df["gender"] = le().fit_transform(df["gender"])

In [15]:
df.head()

   customer_id   age  gender  ...  satisfaction_score customer_level target
0         1001  25.0       1  ...                 8.5         Bronze      1
1         1002  32.0       0  ...                 9.2         Silver      1
2         1003  37.6       0  ...                 7.8           Gold      0
3         1004  45.0       1  ...                 9.8       Platinum      1
4         1005  29.0       2  ...                 6.9         Bronze      0

[5 rows x 15 columns]

In [16]:
from sklearn.preprocessing import OrdinalEncoder as oe

df["customer_level"] = oe(categories=[["Bronze", "Silver", "Gold", "Platinum"]]).fit_transform(df[["customer_level"]])

In [17]:
from sklearn.preprocessing import OneHotEncoder 

ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(df[["preferred_device"]])

In [18]:
encoded_df = pd.DataFrame(
    encoded,
    columns = ohe.get_feature_names_out(["preferred_device"])
)

In [19]:
df = pd.concat([df,encoded_df],axis=1)

In [20]:
df.head(10)

   customer_id   age  ...  preferred_device_Tablet  preferred_device_None
0         1001  25.0  ...                      0.0                    0.0
1         1002  32.0  ...                      0.0                    0.0
2         1003  37.6  ...                      1.0                    0.0
3         1004  45.0  ...                      0.0                    0.0
4         1005  29.0  ...                      0.0                    0.0
5         1006  41.0  ...                      0.0                    0.0
6         1007  38.0  ...                      0.0                    1.0
7         1008  37.6  ...                      1.0                    0.0
8         1009  27.0  ...                      0.0                    0.0
9         1010  50.0  ...                      0.0                    0.0

[10 rows x 19 columns]

In [23]:
from sklearn.preprocessing import StandardScaler 

scaler = StandardScaler()

df[["age", "income"]] = scaler.fit_transform(
    df[["age", "income"]]
)

In [24]:
from sklearn.preprocessing import MinMaxScaler

mmscale = MinMaxScaler()

df[["satisfaction_score"]] = mmscale.fit_transform(
    df[["satisfaction_score"]]
)

In [32]:
df.head(10)

   customer_id       age  ...  preferred_device_Tablet  preferred_device_None
0         1001 -1.341641  ...                      0.0                    0.0
1         1002 -0.596285  ...                      0.0                    0.0
2         1003  0.000000  ...                      1.0                    0.0
3         1004  0.787948  ...                      0.0                    0.0
4         1005 -0.915723  ...                      0.0                    0.0
5         1006  0.362030  ...                      0.0                    0.0
6         1007  0.042592  ...                      0.0                    1.0
7         1008  0.000000  ...                      1.0                    0.0
8         1009 -1.128682  ...                      0.0                    0.0
9         1010  1.320345  ...                      0.0                    0.0

[10 rows x 19 columns]

In [ ]:
from sklearn.impute import KNNImputer, SimpleImputer

knn = KNNImputer(n_neighbors=2)

df = pd.DataFrame(
    knn.fit_transform(df),
    columns=df.columns
)

In [33]:
imputer = SimpleImputer(strategy="mean")

df[["age"]] = imputer.fit_transform(df[["age"]])

df.head(10)

   customer_id       age  ...  preferred_device_Tablet  preferred_device_None
0         1001 -1.341641  ...                      0.0                    0.0
1         1002 -0.596285  ...                      0.0                    0.0
2         1003  0.000000  ...                      1.0                    0.0
3         1004  0.787948  ...                      0.0                    0.0
4         1005 -0.915723  ...                      0.0                    0.0
5         1006  0.362030  ...                      0.0                    0.0
6         1007  0.042592  ...                      0.0                    1.0
7         1008  0.000000  ...                      1.0                    0.0
8         1009 -1.128682  ...                      0.0                    0.0
9         1010  1.320345  ...                      0.0                    0.0

[10 rows x 19 columns]